INSERT INTO users (name, age) VALUES ('Chris', 40);
INSERT INTO users (name, age) VALUES ('Robert', 56);
INSERT INTO users (name, age) VALUES ('Chris', 38);
INSERT INTO users (name, age) VALUES ('Scarlett', 37);
INSERT INTO users (name, age) VALUES ('Tom', 25);
INSERT INTO users (name, age) VALUES ('Mark', 54);
INSERT INTO users (name, age) VALUES ('Brie', 32);
INSERT INTO users (name, age) VALUES ('Chadwick', 44);
INSERT INTO users (name, age) VALUES ('Jeremy', 50);
INSERT INTO users (name, age) VALUES ('Tom', 40);
INSERT INTO users (name, age) VALUES ('Benedict', 45);
INSERT INTO users (name, age) VALUES ('Samuel', 72);
INSERT INTO users (name, age) VALUES ('Paul', 52);
INSERT INTO users (name, age) VALUES ('Elizabeth', 32);
INSERT INTO users (name, age) VALUES ('Sebastian', 39);
INSERT INTO users (name, age) VALUES ('Paul', 50);
INSERT INTO users (name, age) VALUES ('Jon', 55);
INSERT INTO users (name, age) VALUES ('Zoe', 43);
INSERT INTO users (name, age) VALUES ('Anthony', 43);
INSERT INTO users (name, age) VALUES ('Karen', 34);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Iron Man', 'Action, Superhero', 140, 2007, 2008);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('The Incredible Hulk', 'Action, Superhero', 137, 2007, 2008);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Iron Man 2', 'Action, Superhero', 200, 2009, 2010);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Thor', 'Action, Superhero', 150, 2010, 2011);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Captain America: The First Avenger', 'Action, Superhero', 140, 2010, 2011);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('The Avengers', 'Action, Superhero', 220, 2011, 2012);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Iron Man 3', 'Action, Superhero', 200, 2012, 2013);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Thor: The Dark World', 'Action, Superhero', 150, 2012, 2013);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Captain America: The Winter Soldier', 'Action, Superhero', 170, 2013, 2014);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Guardians of the Galaxy', 'Action, Superhero', 220, 2013, 2014);
INSERT INTO pledges (amount, user_id, project_id) VALUES (140, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (137, 6, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (140, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (220, 4, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 10, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (170, 15, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (220, 18, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 17, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 19, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (NULL, 20, 10);